version: '2'
services:
  zipkin-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zipkin
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:management
    expose:
      - 5672
    ports:
      - "15672:15672"
      - "5672:5672"